FROM golang:alpine
MAINTAINER "Shuji Yamada <s-yamada@arukas.io>"

RUN apk add --update git bash zip
RUN go get github.com/tools/godep
RUN go get github.com/arukasio/cli

WORKDIR $GOPATH/src/github.com/arukasio/cli

RUN godep restore -v .../.
RUN ARUKAS_DEV=1 scripts/build.sh

WORKDIR $GOPATH
ENTRYPOINT ["bin/arukas"]
